/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GodmodeRouteImport } from './routes/godmode'
import { Route as GodmodeShellRouteImport } from './routes/godmode/_shell'
import { Route as GodmodeLoginRouteImport } from './routes/godmode/login'
import { Route as ApiWebhooksSendWaOtpRouteImport } from './routes/api/webhooks/send-wa-otp'
import { Route as GodmodeShellIndexRouteImport } from './routes/godmode/_shell/index'
import { Route as GodmodeShellClaimsRouteImport } from './routes/godmode/_shell/claims'
import { Route as GodmodeShellLeadsRouteImport } from './routes/godmode/_shell/leads'
import { Route as GodmodeShellMembersIndexRouteImport } from './routes/godmode/_shell/members/index'
import { Route as GodmodeShellMembersMemberIdRouteImport } from './routes/godmode/_shell/members/$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GodmodeRoute = GodmodeRouteImport.update({
  id: '/godmode',
  path: '/godmode',
  getParentRoute: () => rootRouteImport,
} as any)
const GodmodeShellRoute = GodmodeShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => GodmodeRoute,
} as any)
const GodmodeLoginRoute = GodmodeLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GodmodeRoute,
} as any)
const ApiWebhooksSendWaOtpRoute = ApiWebhooksSendWaOtpRouteImport.update({
  id: '/api/webhooks/send-wa-otp',
  path: '/api/webhooks/send-wa-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const GodmodeShellIndexRoute = GodmodeShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GodmodeShellRoute,
} as any)
const GodmodeShellClaimsRoute = GodmodeShellClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => GodmodeShellRoute,
} as any)
const GodmodeShellLeadsRoute = GodmodeShellLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => GodmodeShellRoute,
} as any)
const GodmodeShellMembersIndexRoute =
  GodmodeShellMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => GodmodeShellRoute,
  } as any)
const GodmodeShellMembersMemberIdRoute =
  GodmodeShellMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => GodmodeShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/godmode': typeof GodmodeRouteWithChildren
  '/godmode/login': typeof GodmodeLoginRoute
  '/api/webhooks/send-wa-otp': typeof ApiWebhooksSendWaOtpRoute
  '/godmode/claims': typeof GodmodeShellClaimsRoute
  '/godmode/leads': typeof GodmodeShellLeadsRoute
  '/godmode/': typeof GodmodeShellIndexRoute
  '/godmode/members/$memberId': typeof GodmodeShellMembersMemberIdRoute
  '/godmode/members/': typeof GodmodeShellMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/godmode': typeof GodmodeShellIndexRoute
  '/godmode/login': typeof GodmodeLoginRoute
  '/api/webhooks/send-wa-otp': typeof ApiWebhooksSendWaOtpRoute
  '/godmode/claims': typeof GodmodeShellClaimsRoute
  '/godmode/leads': typeof GodmodeShellLeadsRoute
  '/godmode/members/$memberId': typeof GodmodeShellMembersMemberIdRoute
  '/godmode/members': typeof GodmodeShellMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/godmode': typeof GodmodeRouteWithChildren
  '/godmode/_shell': typeof GodmodeShellRouteWithChildren
  '/godmode/login': typeof GodmodeLoginRoute
  '/api/webhooks/send-wa-otp': typeof ApiWebhooksSendWaOtpRoute
  '/godmode/_shell/claims': typeof GodmodeShellClaimsRoute
  '/godmode/_shell/leads': typeof GodmodeShellLeadsRoute
  '/godmode/_shell/': typeof GodmodeShellIndexRoute
  '/godmode/_shell/members/$memberId': typeof GodmodeShellMembersMemberIdRoute
  '/godmode/_shell/members/': typeof GodmodeShellMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/godmode'
    | '/godmode/login'
    | '/api/webhooks/send-wa-otp'
    | '/godmode/claims'
    | '/godmode/leads'
    | '/godmode/'
    | '/godmode/members/$memberId'
    | '/godmode/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/godmode'
    | '/godmode/login'
    | '/api/webhooks/send-wa-otp'
    | '/godmode/claims'
    | '/godmode/leads'
    | '/godmode/members/$memberId'
    | '/godmode/members'
  id:
    | '__root__'
    | '/'
    | '/godmode'
    | '/godmode/_shell'
    | '/godmode/login'
    | '/api/webhooks/send-wa-otp'
    | '/godmode/_shell/claims'
    | '/godmode/_shell/leads'
    | '/godmode/_shell/'
    | '/godmode/_shell/members/$memberId'
    | '/godmode/_shell/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GodmodeRoute: typeof GodmodeRouteWithChildren
  ApiWebhooksSendWaOtpRoute: typeof ApiWebhooksSendWaOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godmode': {
      id: '/godmode'
      path: '/godmode'
      fullPath: '/godmode'
      preLoaderRoute: typeof GodmodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godmode/_shell': {
      id: '/godmode/_shell'
      path: ''
      fullPath: '/godmode'
      preLoaderRoute: typeof GodmodeShellRouteImport
      parentRoute: typeof GodmodeRoute
    }
    '/godmode/login': {
      id: '/godmode/login'
      path: '/login'
      fullPath: '/godmode/login'
      preLoaderRoute: typeof GodmodeLoginRouteImport
      parentRoute: typeof GodmodeRoute
    }
    '/api/webhooks/send-wa-otp': {
      id: '/api/webhooks/send-wa-otp'
      path: '/api/webhooks/send-wa-otp'
      fullPath: '/api/webhooks/send-wa-otp'
      preLoaderRoute: typeof ApiWebhooksSendWaOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godmode/_shell/': {
      id: '/godmode/_shell/'
      path: '/'
      fullPath: '/godmode/'
      preLoaderRoute: typeof GodmodeShellIndexRouteImport
      parentRoute: typeof GodmodeShellRoute
    }
    '/godmode/_shell/claims': {
      id: '/godmode/_shell/claims'
      path: '/claims'
      fullPath: '/godmode/claims'
      preLoaderRoute: typeof GodmodeShellClaimsRouteImport
      parentRoute: typeof GodmodeShellRoute
    }
    '/godmode/_shell/leads': {
      id: '/godmode/_shell/leads'
      path: '/leads'
      fullPath: '/godmode/leads'
      preLoaderRoute: typeof GodmodeShellLeadsRouteImport
      parentRoute: typeof GodmodeShellRoute
    }
    '/godmode/_shell/members/': {
      id: '/godmode/_shell/members/'
      path: '/members'
      fullPath: '/godmode/members/'
      preLoaderRoute: typeof GodmodeShellMembersIndexRouteImport
      parentRoute: typeof GodmodeShellRoute
    }
    '/godmode/_shell/members/$memberId': {
      id: '/godmode/_shell/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/godmode/members/$memberId'
      preLoaderRoute: typeof GodmodeShellMembersMemberIdRouteImport
      parentRoute: typeof GodmodeShellRoute
    }
  }
}

interface GodmodeShellRouteChildren {
  GodmodeShellClaimsRoute: typeof GodmodeShellClaimsRoute
  GodmodeShellLeadsRoute: typeof GodmodeShellLeadsRoute
  GodmodeShellIndexRoute: typeof GodmodeShellIndexRoute
  GodmodeShellMembersMemberIdRoute: typeof GodmodeShellMembersMemberIdRoute
  GodmodeShellMembersIndexRoute: typeof GodmodeShellMembersIndexRoute
}

const GodmodeShellRouteChildren: GodmodeShellRouteChildren = {
  GodmodeShellClaimsRoute: GodmodeShellClaimsRoute,
  GodmodeShellLeadsRoute: GodmodeShellLeadsRoute,
  GodmodeShellIndexRoute: GodmodeShellIndexRoute,
  GodmodeShellMembersMemberIdRoute: GodmodeShellMembersMemberIdRoute,
  GodmodeShellMembersIndexRoute: GodmodeShellMembersIndexRoute,
}

const GodmodeShellRouteWithChildren = GodmodeShellRoute._addFileChildren(
  GodmodeShellRouteChildren,
)

interface GodmodeRouteChildren {
  GodmodeShellRoute: typeof GodmodeShellRouteWithChildren
  GodmodeLoginRoute: typeof GodmodeLoginRoute
}

const GodmodeRouteChildren: GodmodeRouteChildren = {
  GodmodeShellRoute: GodmodeShellRouteWithChildren,
  GodmodeLoginRoute: GodmodeLoginRoute,
}

const GodmodeRouteWithChildren =
  GodmodeRoute._addFileChildren(GodmodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GodmodeRoute: GodmodeRouteWithChildren,
  ApiWebhooksSendWaOtpRoute: ApiWebhooksSendWaOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
